name: Set the version property in CITATION.cff to the GitHub release version
on:
  workflow_call:

jobs:
  update_citation_file:
    name: Deploy docs
    runs-on: ubuntu-22.04
    outputs:
      RESOURCE_VERSION: ${{ steps.changes_check.outputs.RESOURCE_VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Get current date
        run: |
          echo "CURRENT_DATE=$(date '+%Y-%m-%d')" >> $GITHUB_ENV

      - name: Update CITATION.cff version
        uses: mikefarah/yq@v4.34.2
        with:
          cmd: yq eval -i '.version="${{ github.event.release.tag_name }}"' CITATION.cff

      - name: Update CITATION.cff date-released
        uses: mikefarah/yq@v4.34.2
        with:
          cmd: yq eval -i '.date-released="${{ env.CURRENT_DATE }}"' CITATION.cff

      - name: Check for changes
        id: changes_check
        run: |
          echo "RESOURCE_VERSION=${{ github.event.release.tag_name }}" >> "$GITHUB_OUTPUT"
          git diff-index --quiet HEAD || echo "changes=true" >> $GITHUB_ENV

      - name: Commit updated CITATION.cff file
        if: env.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add CITATION.cff
          git commit -m "Automated version update of CITATION.cff to ${{ github.event.release.tag_name }}"
          git push